export default {
    task: [
        "Address",
        "Adjust",
        "Amend",
        "Correct",
        "Eliminate",
        "Ensure",
        "Fix",
        "Handle",
        "Improve",
        "Mend",
        "Patch",
        "Rectify",
        "Repair",
        "Resolve",
        "Restore",
    ],
    what: [
        "the anomaly",
        "the bug",
        "the blunder",
        "the complication",
        "the defect",
        "the discrepancy",
        "the error",
        "the fault",
        "the flaw",
        "the glitch",
        "the hiccup",
        "the inconsistency",
        "the inaccuracy",
        "the irregularity",
        "the issue",
        "the lapse",
        "the loophole",
        "the malfunction",
        "the miscalculation",
        "the mistake",
        "the misstep",
        "the obstacle",
        "the oversight",
        "the problem",
        "the shortcoming",
        "the slip-up",
        "the snag",
        "the weakness",
        "the vulnerability",
    ],
    where: [
        "in the algorithm",
        "in the application",
        "in the architecture",
        "in the backend",
        "in the code",
        "in the component",
        "in the configuration",
        "in the environment",
        "in the framework",
        "in the frontend",
        "in the function",
        "in the infrastructure",
        "in the interface",
        "in the library",
        "in the logic",
        "in the method",
        "in the module",
        "in the operation",
        "in the platform",
        "in the process",
        "in the program",
        "in the routine",
        "in the script",
        "in the sequence",
        "in the service",
        "in the setup",
        "in the software",
        "in the system",
        "in the tool",
        "in the workflow",
    ],
};
